# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - smartxphones-backend

on:
  push:
    branches:
      - master
    paths:
      - 'ecommerce-backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: update db url
        run: sed -i 's/<db_url>/${{ secrets.DB_URI }}/' ecommerce-backend/src/main/resources/application.properties

      - name: update db username
        run: sed -i 's/<db_username>/${{ secrets.DB_USERNAME }}/' ecommerce-backend/src/main/resources/application.properties

      - name: update db password
        run: sed -i 's/<db_password>/${{ secrets.DB_PASSWORD }}/' ecommerce-backend/src/main/resources/application.properties

      - name: update twilio sid
        run: sed -i 's/<twilio_sid>/${{ secrets.TWILIO_SID }}/' ecommerce-backend/src/main/resources/application.properties

      - name: update twilio auth token
        run: sed -i 's/<twilio_authtoen>/${{ secrets.TWILIO_AUTHTOKEN }}/' ecommerce-backend/src/main/resources/application.properties

      - name: update mailtrap username
        run: sed -i 's/<mailtrap_username>/${{ secrets.MAILTRAP_USERNAME }}/' ecommerce-backend/src/main/resources/application.properties

      - name: update mailtrap password
        run: sed -i 's/<mailtrap_password>/${{ secrets.MAILTRAP_PASSWORD }}/' ecommerce-backend/src/main/resources/application.properties
      

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: |
          cd ecommerce-backend
          mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/ecommerce-backend/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'smartxphones-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F6B81A2E919D4C4DBDEFF6B0268E1FA2 }}
          package: '*.jar'
